services:
  mysql:
    image: mysql:8.4
    container_name: iosra_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: IOSRA_DB
      TZ: UTC
    volumes:
      - mysqldata:/var/lib/mysql
    # CHỈ lắng nghe trên loopback của VPS (an toàn, dùng SSH/DBeaver tunnel)
    ports:
      - "127.0.0.1:3306:3306"
    networks: [ iosra ]
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -p$$MYSQL_ROOT_PASSWORD --silent"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build:
      context: .
      dockerfile: Main/Dockerfile
    container_name: iosra_api
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    volumes:
      - ./Main/appsettings.Secret.json:/app/appsettings.Secret.json:ro
    depends_on:
      mysql:
        condition: service_healthy
    networks: [ iosra ]
    # KHÔNG expose port trực tiếp. Caddy reverse proxy vào api:8080

  caddy:
    image: caddy:2.8
    container_name: iosra_caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - api
    networks: [ iosra ]

  redis:
    image: redis:7
    container_name: iosra_redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    networks: [ iosra ]

volumes:
  mysqldata:

networks:
  iosra:
