name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd /opt/iosra
            # Đảm bảo KHÔNG còn file thủ công khác
            git fetch --all --prune
            git reset --hard origin/main
            # Build & chạy theo compose TRONG REPO
            docker compose up -d --build
            docker compose ps
